create table if not exists public.fetched_products (
  id integer generated by default as identity primary key,
  batch_id varchar(64) not null,
  config_id integer not null,
  trigger_source varchar(20) not null,
  product_id varchar(255) not null,
  title text,
  price integer,
  url text,
  image_url text,
  publish_time text,
  location text,
  fetched_at timestamptz not null default now()
);

create index if not exists fetched_products_batch_id_idx
  on public.fetched_products (batch_id);

create index if not exists fetched_products_config_id_idx
  on public.fetched_products (config_id);

create index if not exists fetched_products_product_id_idx
  on public.fetched_products (product_id);

create index if not exists fetched_products_fetched_at_idx
  on public.fetched_products (fetched_at);

alter table public.fetched_products disable row level security;
