-- xianyu-auto-search Supabase bootstrap
-- Run this in Supabase SQL Editor for a fresh project.
--
-- Note:
-- This project currently uses the anon/publishable key on the server.
-- For a quick local setup, the script disables RLS on the app tables.
-- If you want stricter security later, switch to service_role on the server
-- or re-enable RLS and add explicit policies.

create table if not exists public.health_check (
  id integer generated by default as identity not null,
  updated_at timestamptz default now()
);

create table if not exists public.monitor_configs (
  id integer generated by default as identity primary key,
  search_keyword varchar(255) not null,
  price_min integer,
  price_max integer,
  region_province varchar(50),
  region_city varchar(50),
  region_district varchar(50),
  time_range varchar(50),
  sort_type varchar(50),
  cron_expression varchar(100) not null default '0 */30 * * * *',
  webhook_url text,
  cookies text,
  is_active boolean not null default true,
  browser_headless boolean not null default false,
  browser_save_debug boolean not null default true,
  browser_channel varchar(20),
  browser_executable_path text,
  browser_user_data_dir text,
  created_at timestamptz not null default now(),
  updated_at timestamptz default now()
);

create index if not exists monitor_configs_active_idx
  on public.monitor_configs (is_active);

create table if not exists public.sent_products (
  id integer generated by default as identity primary key,
  product_id varchar(255) not null,
  config_id integer not null,
  title text,
  price integer,
  url text,
  image_url text,
  sent_at timestamptz not null default now()
);

create index if not exists sent_products_product_id_idx
  on public.sent_products (product_id);

create index if not exists sent_products_config_id_idx
  on public.sent_products (config_id);

create index if not exists sent_products_sent_at_idx
  on public.sent_products (sent_at);

create table if not exists public.fetched_products (
  id integer generated by default as identity primary key,
  batch_id varchar(64) not null,
  config_id integer not null,
  trigger_source varchar(20) not null,
  product_id varchar(255) not null,
  title text,
  price integer,
  url text,
  image_url text,
  publish_time text,
  location text,
  fetched_at timestamptz not null default now()
);

create index if not exists fetched_products_batch_id_idx
  on public.fetched_products (batch_id);

create index if not exists fetched_products_config_id_idx
  on public.fetched_products (config_id);

create index if not exists fetched_products_product_id_idx
  on public.fetched_products (product_id);

create index if not exists fetched_products_fetched_at_idx
  on public.fetched_products (fetched_at);

alter table public.monitor_configs disable row level security;
alter table public.sent_products disable row level security;
alter table public.fetched_products disable row level security;
alter table public.health_check disable row level security;
